--Infra = warehouse, database.
--SNOWFLAKE_LEARNING_DB-- create warehouse
CREATE WAREHOUSE IF NOT EXISTS WH_PRODUCT_ANALYTICS
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

-- use warehouse
USE WAREHOUSE WH_PRODUCT_ANALYTICS;


-- Create database and raw schema
CREATE DATABASE IF NOT EXISTS PRODUCT_ANALYTICS_DB;