--Raw schema defines table structure
USE DATABASE PRODUCT_ANALYTICS_DB;

CREATE SCHEMA IF NOT EXISTS RAW;

-- Raw event table (landing from Glue)
CREATE OR REPLACE TABLE RAW.EVENTS_RAW (
    RAW_PAYLOAD     VARIANT,
    INGESTED_AT     TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);

ALTER TABLE RAW.EVENTS_RAW DROP COLUMN FEATURE_NAME, EVENT_TS;
