--analytics_schema defines modeling layer
USE DATABASE PRODUCT_ANALYTICS_DB;

CREATE SCHEMA IF NOT EXISTS ANALYTICS;

-- Dimension: Users
CREATE OR REPLACE TABLE ANALYTICS.DIM_USERS (
    USER_ID         STRING,
    FIRST_SEEN_AT   TIMESTAMP_TZ,
    LAST_SEEN_AT    TIMESTAMP_TZ
);

-- Dimension: Features
CREATE OR REPLACE TABLE ANALYTICS.DIM_FEATURES (
    FEATURE_NAME    STRING,
    FIRST_SEEN_AT   TIMESTAMP_TZ
);

-- Fact: Individual events
CREATE OR REPLACE TABLE ANALYTICS.FACT_EVENTS (
    EVENT_ID        STRING,
    USER_ID         STRING,
    EVENT_NAME      STRING,
    FEATURE_NAME    STRING,
    EVENT_TS        TIMESTAMP_TZ,
    EVENT_DATE      DATE,
    CREATED_AT      TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);
