--Stream should exist independently of a specific ingestion run and upstream of transformation
USE DATABASE PRODUCT_ANALYTICS_DB;
USE SCHEMA RAW;

CREATE OR REPLACE STREAM RAW.RAW_EVENTS_STREAM
ON TABLE RAW.EVENTS_RAW
APPEND_ONLY = TRUE;

--SELECT COUNT(*) FROM RAW.RAW_EVENTS_STREAM;

--USE SCHEMA ANALYTICS;
CREATE OR REPLACE STREAM ANALYTICS.FACT_EVENTS_STREAM
ON TABLE ANALYTICS.FACT_EVENTS
APPEND_ONLY = TRUE;

--SELECT COUNT(*) FROM ANALYTICS.FACT_EVENTS_STREAM;
--DROP STREAM IF EXISTS ANALYTICS.FACT_EVENTS_STREAM;
--SHOW STREAMS;