--Ingestion loads data
USE ROLE ACCOUNTADMIN;
USE DATABASE PRODUCT_ANALYTICS_DB;
USE SCHEMA RAW;

-- File format
CREATE OR REPLACE FILE FORMAT RAW.RAW_JSON_FORMAT TYPE = 'JSON';

-- External stage
CREATE OR REPLACE STAGE RAW.RAW_EVENTS_STAGE
URL = 's3://saas-product-analytics-raw/processed/'
STORAGE_INTEGRATION = s3_raw_integration
FILE_FORMAT = RAW.RAW_JSON_FORMAT;

-- Validate
LIST @RAW.RAW_EVENTS_STAGE;

-- Load
COPY INTO RAW.EVENTS_RAW (RAW_PAYLOAD)
FROM @RAW.RAW_EVENTS_STAGE
FILE_FORMAT = (FORMAT_NAME = RAW.RAW_JSON_FORMAT);

--SELECT COUNT(*) FROM RAW.EVENTS_RAW;
--SELECT COUNT(*) FROM ANALYTICS.FACT_EVENTS;
--SELECT COUNT(*) FROM PRODUCT_ANALYTICS_DB.ANALYTICS.FACT_EVENTS;

--USE ROLE ACCOUNTADMIN;
--USE DATABASE PRODUCT_ANALYTICS_DB;
--USE SCHEMA RAW;

CREATE OR REPLACE PIPE RAW.EVENTS_RAW_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO PRODUCT_ANALYTICS_DB.RAW.EVENTS_RAW (RAW_PAYLOAD)
FROM @PRODUCT_ANALYTICS_DB.RAW.RAW_EVENTS_STAGE
FILE_FORMAT = (FORMAT_NAME = PRODUCT_ANALYTICS_DB.RAW.RAW_JSON_FORMAT);

--DESC PIPE RAW.EVENTS_RAW_PIPE;
SHOW PIPES;
SELECT SYSTEM$PIPE_STATUS('PRODUCT_ANALYTICS_DB.RAW.EVENTS_RAW_PIPE');