--Transformation consumes data along with MERGE + stream logic
USE DATABASE PRODUCT_ANALYTICS_DB;
USE SCHEMA ANALYTICS;

INSERT INTO FACT_EVENTS
SELECT
    RAW_PAYLOAD:RAW_PAYLOAD:event_id::STRING        AS EVENT_ID,
    RAW_PAYLOAD:RAW_PAYLOAD:user_id::STRING         AS USER_ID,
    RAW_PAYLOAD:RAW_PAYLOAD:event_name::STRING      AS EVENT_NAME,
    RAW_PAYLOAD:RAW_PAYLOAD:properties:feature_name::STRING    AS FEATURE_NAME,
    RAW_PAYLOAD:RAW_PAYLOAD:timestamp::TIMESTAMP_TZ AS EVENT_TS,
    TO_DATE(RAW_PAYLOAD:RAW_PAYLOAD:timestamp::TIMESTAMP_TZ) AS EVENT_DATE,
    CURRENT_TIMESTAMP() AS CREATED_AT
FROM PRODUCT_ANALYTICS_DB.RAW.EVENTS_RAW;

--TRUNCATE TABLE ANALYTICS.DIM_USERS;

INSERT INTO ANALYTICS.DIM_USERS 
    SELECT USER_ID, 
    MIN(EVENT_TS) AS FIRST_SEEN_AT, 
    MAX(EVENT_TS) AS LAST_SEEN_AT 
FROM ANALYTICS.FACT_EVENTS 
GROUP BY (USER_ID);

--TRUNCATE TABLE ANALYTICS.DIM_FEATURES;

INSERT INTO ANALYTICS.DIM_FEATURES 
SELECT 
    FEATURE_NAME, 
    MIN(EVENT_TS) AS FIRST_SEEN_AT
FROM ANALYTICS.FACT_EVENTS 
WHERE FEATURE_NAME IS NOT NULL 
GROUP BY (FEATURE_NAME);

-- SELECT * FROM ANALYTICS.DIM_FEATURES;

--TRUNCATE TABLE ANALYTICS.FACT_DAILY_PRODUCT_METRICS;
INSERT INTO ANALYTICS.FACT_DAILY_PRODUCT_METRICS
SELECT 
    EVENT_DATE, 
    COUNT(DISTINCT USER_ID) AS DAU,
    COUNT(*) AS EVENTS_COUNT, 
    COUNT (CASE WHEN FEATURE_NAME IS NOT NULL THEN 1 END) AS UNIQUE_FEATURES_USED,
    CURRENT_TIMESTAMP() AS CREATED_AT 
FROM ANALYTICS.FACT_EVENTS 
GROUP BY (EVENT_DATE);

SELECT * FROM ANALYTICS.FACT_DAILY_PRODUCT_METRICS ORDER BY EVENT_DATE;

