USE ROLE ACCOUNTADMIN;
USE DATABASE PRODUCT_ANALYTICS_DB;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE TASK TASK_LOAD_FACT_EVENTS
WAREHOUSE = WH_PRODUCT_ANALYTICS
SCHEDULE = '1 MINUTE'
WHEN SYSTEM$STREAM_HAS_DATA('RAW.RAW_EVENTS_STREAM')
AS
    MERGE INTO PRODUCT_ANALYTICS_DB.ANALYTICS.FACT_EVENTS tgt
    USING (
        SELECT
            RAW_PAYLOAD:RAW_PAYLOAD:event_id::STRING        AS EVENT_ID,
            RAW_PAYLOAD:RAW_PAYLOAD:user_id::STRING         AS USER_ID,
            RAW_PAYLOAD:RAW_PAYLOAD:event_name::STRING      AS EVENT_NAME,
            RAW_PAYLOAD:RAW_PAYLOAD:properties:feature_name::STRING AS FEATURE_NAME,
            RAW_PAYLOAD:RAW_PAYLOAD:timestamp::TIMESTAMP_TZ AS EVENT_TS,
            TO_DATE(RAW_PAYLOAD:RAW_PAYLOAD:timestamp::TIMESTAMP_TZ) AS EVENT_DATE
        FROM PRODUCT_ANALYTICS_DB.RAW.RAW_EVENTS_STREAM
    ) src
    ON tgt.EVENT_ID = src.EVENT_ID
    WHEN NOT MATCHED THEN
    INSERT (
        EVENT_ID,
        USER_ID,
        EVENT_NAME,
        FEATURE_NAME,
        EVENT_TS,
        EVENT_DATE,
        CREATED_AT
    )
    VALUES (
        src.EVENT_ID,
        src.USER_ID,
        src.EVENT_NAME,
        src.FEATURE_NAME,
        src.EVENT_TS,
        src.EVENT_DATE,
        CURRENT_TIMESTAMP()
    );

--ALTER TASK TASK_LOAD_FACT_EVENTS RESUME;
--ALTER TASK TASK_UPDATE_DAILY_METRICS RESUME;