CREATE OR REPLACE TASK PRODUCT_ANALYTICS_DB.ANALYTICS.TASK_UPDATE_DAILY_METRICS
WAREHOUSE = WH_PRODUCT_ANALYTICS
SCHEDULE = '1 MINUTE'
WHEN SYSTEM$STREAM_HAS_DATA('PRODUCT_ANALYTICS_DB.ANALYTICS.FACT_EVENTS_STREAM')
AS
MERGE INTO PRODUCT_ANALYTICS_DB.ANALYTICS.FACT_DAILY_PRODUCT_METRICS tgt
USING (
    SELECT
        EVENT_DATE,
        COUNT(DISTINCT USER_ID) AS DAU,
        COUNT(*) AS EVENTS_COUNT,
        COUNT(DISTINCT FEATURE_NAME) AS UNIQUE_FEATURES_USED
    FROM PRODUCT_ANALYTICS_DB.ANALYTICS.FACT_EVENTS
    WHERE EVENT_DATE IN (
        SELECT DISTINCT EVENT_DATE
        FROM PRODUCT_ANALYTICS_DB.ANALYTICS.FACT_EVENTS_STREAM
    )
    GROUP BY EVENT_DATE
) src
ON tgt.EVENT_DATE = src.EVENT_DATE
WHEN MATCHED THEN UPDATE SET
    DAU = src.DAU,
    EVENTS_COUNT = src.EVENTS_COUNT,
    UNIQUE_FEATURES_USED = src.UNIQUE_FEATURES_USED
WHEN NOT MATCHED THEN INSERT (
    EVENT_DATE,
    DAU,
    EVENTS_COUNT,
    UNIQUE_FEATURES_USED,
    CREATED_AT
)
VALUES (
    src.EVENT_DATE,
    src.DAU,
    src.EVENTS_COUNT,
    src.UNIQUE_FEATURES_USED,
    CURRENT_TIMESTAMP()
);