USE DATABASE PRODUCT_ANALYTICS_DB;

CREATE SCHEMA IF NOT EXISTS ANALYTICS;

-- Dimension: Users
CREATE OR REPLACE TABLE ANALYTICS.DIM_USERS (
    USER_ID         NUMBER PRIMARY KEY,
    FIRST_SEEN_AT   TIMESTAMP_TZ,
    LAST_SEEN_AT    TIMESTAMP_TZ
);

-- Dimension: Features
CREATE OR REPLACE TABLE ANALYTICS.DIM_FEATURES (
    FEATURE_NAME    STRING PRIMARY KEY,
    FIRST_SEEN_AT   TIMESTAMP_TZ
);

-- Fact: Individual events
CREATE OR REPLACE TABLE ANALYTICS.FACT_EVENTS (
    EVENT_ID        NUMBER PRIMARY KEY,
    USER_ID         NUMBER,
    EVENT_NAME      STRING,
    FEATURE_NAME    STRING,
    EVENT_TS        TIMESTAMP_TZ,
    EVENT_DATE      DATE,
    CREATED_AT      TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);

-- Aggregated: Daily product usage metrics
CREATE OR REPLACE TABLE ANALYTICS.FACT_DAILY_PRODUCT_METRICS (
    EVENT_DATE              DATE,
    DAU                     NUMBER,  -- daily active users
    EVENTS_COUNT            NUMBER,
    UNIQUE_FEATURES_USED    NUMBER,
    CREATED_AT              TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (EVENT_DATE)
);

