
-- Create database and raw schema
CREATE DATABASE IF NOT EXISTS PRODUCT_ANALYTICS_DB;
USE DATABASE PRODUCT_ANALYTICS_DB;

CREATE SCHEMA IF NOT EXISTS RAW;

-- Raw event table (landing from Glue)
CREATE OR REPLACE TABLE RAW.EVENTS_RAW (
    EVENT_ID        NUMBER AUTOINCREMENT,
    USER_ID         NUMBER,
    EVENT_NAME      STRING,
    FEATURE_NAME    STRING,
    EVENT_TS        TIMESTAMP_TZ,
    RAW_PAYLOAD     VARIANT,
    INGESTED_AT     TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);
